import { createAsyncActionCreators } from '../utils';

const TOGGLE_NOTIFICATION_CENTER_REQUEST = 'TOGGLE_NOTIFICATION_CENTER_REQUEST';
const TOGGLE_NOTIFICATION_CENTER_SUCCESS = 'TOGGLE_NOTIFICATION_CENTER_SUCCESS';
const TOGGLE_NOTIFICATION_CENTER_FAILURE = 'TOGGLE_NOTIFICATION_CENTER_FAILURE';

export const toggleNotificationCenter = createAsyncActionCreators(
  TOGGLE_NOTIFICATION_CENTER_REQUEST,
  TOGGLE_NOTIFICATION_CENTER_SUCCESS,
  TOGGLE_NOTIFICATION_CENTER_FAILURE,
)<void, void, Error>();
