import * as React from 'react';
import * as Yup from 'yup';

import * as passwordIcon from '../../assets/Eye.svg';

import { Color } from '../../styles';
import { PasswordIconWrapper, RowWrapper } from '../RequestForm';

import { validatePhone } from '../../utils/validators';
import { ROUTES } from '../Router/consts';

import FormField from '../FormField';
import ResponsiveForm from '../ResponsiveForm';
import SvgIcon from '../SvgIcon/SvgIcon';

export const baseSchema = {
  email: Yup.string()
    .email('Valid email required')
    .required('Required'), // read-only after creation
  firstName: Yup.string().required('Required'),
  id: Yup.string().notRequired(), // generated by BE
  lastName: Yup.string().required('Required'),
  middleInitial: Yup.string().notRequired(),
  phone: Yup.string().required('Required'),
  tmpPassword: Yup.string().required('Required'),
  username: Yup.string().notRequired(), // generated by BE
};

interface Props {
  isPasswordShown?: boolean;
  isSubmitting: boolean;
  isValid: boolean;
  togglePasswordFieldType?: () => void;
  withPasswordField?: boolean;
}

export const UserForm = ({ isPasswordShown, isSubmitting, isValid, togglePasswordFieldType, withPasswordField }: Props) => (
  <ResponsiveForm isSubmitting={isSubmitting} parentRoute={ROUTES.ADMIN_USERS} submitDisabled={isSubmitting || !isValid}>
    <RowWrapper secondElementWidth="55px">
      <FormField label="First Name" type="text" name="firstName" placeholder="Enter first name" />

      <FormField label="MI" type="text" name="middleInitial" />
    </RowWrapper>

    <FormField label="Last Name" type="text" name="lastName" placeholder="Enter last name" />

    <FormField label="Phone Number" type="text" name="phone" maxLength="10" validate={validatePhone} placeholder="Enter phone number" />

    <FormField label="Email" type="email" name="email" placeholder="Enter email" disabled={!withPasswordField} />

    {withPasswordField && (
      <FormField label="Password" type={isPasswordShown ? 'text' : 'password'} name="tmpPassword" placeholder="Enter password">
        <PasswordIconWrapper>
          <SvgIcon
            color={isPasswordShown ? Color.URANUS : Color.COMET}
            hoverColor={Color.JUPITER}
            onClick={togglePasswordFieldType}
            imgSrc={passwordIcon}
            size={25}
          />
        </PasswordIconWrapper>
      </FormField>
    )}
  </ResponsiveForm>
);

export default UserForm;
