import * as Yup from 'yup';

export const baseSchema = {
  email: Yup.string()
    .email('Valid email required')
    .required('Required'), // read-only after creation
  firstName: Yup.string().required('Required'),
  id: Yup.string().notRequired(), // generated by BE
  isAdmin: Yup.boolean(),
  lastName: Yup.string().required('Required'),
  middleName: Yup.string().notRequired(),
  phone: Yup.string()
    .matches(/^\d+$/, 'No characters allowed')
    .min(10, '10 digits required')
    .required('Required'),
  tmpPassword: Yup.string().required('Required'),
  username: Yup.string().notRequired(), // generated by BE
};

export const newUserSchema = Yup.object().shape(baseSchema);

// tmpPassword field not needed to edit users
const { tmpPassword, ...schema } = baseSchema;

export const editUserSchema = Yup.object().shape(schema);
