import { App, User } from '../../types/commons';
import { createAsyncActionCreators } from '../utils';

// GET_ADMIN_APPS
const GET_ADMIN_APPS_REQUEST = 'GET_ADMIN_APPS_REQUEST';
const GET_ADMIN_APPS_SUCCESS = 'GET_ADMIN_APPS_SUCCESS';
const GET_ADMIN_APPS_FAILURE = 'GET_ADMIN_APPS_FAILURE';
// CREATE_ADMIN_APP
const CREATE_ADMIN_APP_REQUEST = 'CREATE_ADMIN_APP_REQUEST';
const CREATE_ADMIN_APP_SUCCESS = 'CREATE_ADMIN_APP_SUCCESS';
const CREATE_ADMIN_APP_FAILURE = 'CREATE_ADMIN_APP_FAILURE';
// UPDATE_ADMIN_APP
const UPDATE_ADMIN_APP_REQUEST = 'UPDATE_ADMIN_APP_REQUEST';
const UPDATE_ADMIN_APP_SUCCESS = 'UPDATE_ADMIN_APP_SUCCESS';
const UPDATE_ADMIN_APP_FAILURE = 'UPDATE_ADMIN_APP_FAILURE';
// DELETE_ADMIN_APP
const DELETE_ADMIN_APP_REQUEST = 'DELETE_ADMIN_APP_REQUEST';
const DELETE_ADMIN_APP_SUCCESS = 'DELETE_ADMIN_APP_SUCCESS';
const DELETE_ADMIN_APP_FAILURE = 'DELETE_ADMIN_APP_FAILURE';
// GET_ADMIN_USERS
const GET_ADMIN_USERS_REQUEST = 'GET_ADMIN_USERS_REQUEST';
const GET_ADMIN_USERS_SUCCESS = 'GET_ADMIN_USERS_SUCCESS';
const GET_ADMIN_USERS_FAILURE = 'GET_ADMIN_USERS_FAILURE';
// CREATE_ADMIN_USER
const CREATE_ADMIN_USER_REQUEST = 'CREATE_ADMIN_USER_REQUEST';
const CREATE_ADMIN_USER_SUCCESS = 'CREATE_ADMIN_USER_SUCCESS';
const CREATE_ADMIN_USER_FAILURE = 'CREATE_ADMIN_USER_FAILURE';
// UPDATE_ADMIN_USER
const UPDATE_ADMIN_USER_REQUEST = 'UPDATE_ADMIN_USER_REQUEST';
const UPDATE_ADMIN_USER_SUCCESS = 'UPDATE_ADMIN_USER_SUCCESS';
const UPDATE_ADMIN_USER_FAILURE = 'UPDATE_ADMIN_USER_FAILURE';
// DELETE_ADMIN_USER
const DELETE_ADMIN_USER_REQUEST = 'DELETE_ADMIN_USER_REQUEST';
const DELETE_ADMIN_USER_SUCCESS = 'DELETE_ADMIN_USER_SUCCESS';
const DELETE_ADMIN_USER_FAILURE = 'DELETE_ADMIN_USER_FAILURE';

// Action Creators
export const getAdminApps = createAsyncActionCreators(GET_ADMIN_APPS_REQUEST, GET_ADMIN_APPS_SUCCESS, GET_ADMIN_APPS_FAILURE)<void, App[], Error>();
export const createAdminApp = createAsyncActionCreators(CREATE_ADMIN_APP_REQUEST, CREATE_ADMIN_APP_SUCCESS, CREATE_ADMIN_APP_FAILURE)<App, App, Error>();
export const updateAdminApp = createAsyncActionCreators(UPDATE_ADMIN_APP_REQUEST, UPDATE_ADMIN_APP_SUCCESS, UPDATE_ADMIN_APP_FAILURE)<App, App, Error>();
export const deleteAdminApp = createAsyncActionCreators(DELETE_ADMIN_APP_REQUEST, DELETE_ADMIN_APP_SUCCESS, DELETE_ADMIN_APP_FAILURE)<App, App, Error>();
export const getAdminUsers = createAsyncActionCreators(GET_ADMIN_USERS_REQUEST, GET_ADMIN_USERS_SUCCESS, GET_ADMIN_USERS_FAILURE)<void, User[], Error>();
export const createAdminUser = createAsyncActionCreators(CREATE_ADMIN_USER_REQUEST, CREATE_ADMIN_USER_SUCCESS, CREATE_ADMIN_USER_FAILURE)<User, User, Error>();
export const updateAdminUser = createAsyncActionCreators(UPDATE_ADMIN_USER_REQUEST, UPDATE_ADMIN_USER_SUCCESS, UPDATE_ADMIN_USER_FAILURE)<User, User, Error>();
export const deleteAdminUser = createAsyncActionCreators(DELETE_ADMIN_USER_REQUEST, DELETE_ADMIN_USER_SUCCESS, DELETE_ADMIN_USER_FAILURE)<User, User, Error>();
