import { ROUTES } from '../components/Router/consts';
import { isProductionEnv } from '../utils/processHelpers';

const WINDOW_PREFIX = 'osLaunchpad';
export const ADMIN_WINDOW = `${WINDOW_PREFIX}Admin`;
export const APP_DIRECTORY_WINDOW = `${WINDOW_PREFIX}AppDirectory`;
export const APP_LAUNCHER_OVERFLOW_WINDOW = `${WINDOW_PREFIX}AppLauncherOverflow`;
export const CONTEXT_MENU = `${WINDOW_PREFIX}ContextMenu`;
export const LAYOUTS_WINDOW = `${WINDOW_PREFIX}Layouts`;
export const LOGIN_WINDOW = `${WINDOW_PREFIX}Login`;
export const MAIN_WINDOW = 'osLaunchpadMain';
export const SETTINGS_WINDOW = `${WINDOW_PREFIX}Settings`;

const isProduction = isProductionEnv();

export const initOnStartWindows = {
  // eventually move admin window out of initOnStartWindows and only initialize on login if isAdmin
  admin: {
    alwaysOnTop: false,
    autoShow: false,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 621,
    defaultWidth: 614,
    frame: false,
    id: ADMIN_WINDOW,
    maxHeight: -1,
    maximizable: false,
    minHeight: 500,
    minWidth: 450,
    minimizable: true,
    name: ADMIN_WINDOW,
    resizable: true,
    saveWindowState: false,
    shadow: true,
    showTaskbarIcon: true,
    url: ROUTES.ADMIN,
    waitForPageLoad: true,
  },
  appDirectory: {
    alwaysOnTop: true,
    autoShow: false,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 542,
    defaultWidth: 510,
    frame: false,
    id: APP_DIRECTORY_WINDOW,
    maxHeight: -1,
    maximizable: false,
    minHeight: 0,
    minWidth: 0,
    minimizable: false,
    name: APP_DIRECTORY_WINDOW,
    resizable: false,
    saveWindowState: false,
    shadow: true,
    showTaskbarIcon: true,
    url: ROUTES.APP_DIRECTORY,
    waitForPageLoad: true,
  },
  appLauncherOverflow: {
    alwaysOnTop: true,
    autoShow: true,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 300,
    defaultWidth: 200,
    frame: false,
    id: APP_LAUNCHER_OVERFLOW_WINDOW,
    maxHeight: -1,
    maximizable: false,
    minHeight: 0,
    minWidth: 0,
    minimizable: false,
    name: APP_LAUNCHER_OVERFLOW_WINDOW,
    opacity: 0,
    resizable: false,
    saveWindowState: false,
    showTaskbarIcon: false,
    url: ROUTES.APP_LAUNCHER_OVERFLOW,
    waitForPageLoad: true,
  },
  contextMenu: {
    alwaysOnTop: true,
    autoShow: false,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 30,
    defaultWidth: 80,
    frame: false,
    id: CONTEXT_MENU,
    maxHeight: -1,
    maximizable: false,
    minHeight: 0,
    minWidth: 0,
    minimizable: false,
    name: CONTEXT_MENU,
    resizable: false,
    saveWindowState: false,
    shadow: true,
    showTaskbarIcon: false,
    url: ROUTES.CONTEXT_MENU,
    waitForPageLoad: true,
  },
  layouts: {
    alwaysOnTop: true,
    autoShow: false,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 100,
    defaultWidth: 50,
    frame: false,
    id: LAYOUTS_WINDOW,
    maxHeight: -1,
    maximizable: false,
    minHeight: 0,
    minWidth: 0,
    minimizable: false,
    name: LAYOUTS_WINDOW,
    resizable: false,
    saveWindowState: false,
    showTaskbarIcon: false,
    url: ROUTES.LAYOUTS,
    waitForPageLoad: true,
  },
  settings: {
    alwaysOnTop: true,
    autoShow: false,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 478,
    defaultWidth: 510,
    frame: false,
    id: SETTINGS_WINDOW,
    maxHeight: -1,
    maximizable: false,
    minHeight: 0,
    minWidth: 0,
    minimizable: false,
    name: SETTINGS_WINDOW,
    resizable: false,
    saveWindowState: false,
    shadow: true,
    showTaskbarIcon: true,
    url: ROUTES.SETTINGS,
    waitForPageLoad: true,
  },
};

const config = {
  ...initOnStartWindows,
  login: {
    alwaysOnTop: false,
    autoShow: true,
    contextMenu: !isProduction,
    defaultCentered: true,
    defaultHeight: 350,
    defaultWidth: 350,
    frame: false,
    id: LOGIN_WINDOW,
    maxHeight: -1,
    maximizable: false,
    minHeight: 0,
    minWidth: 0,
    minimizable: false,
    name: LOGIN_WINDOW,
    resizable: false,
    saveWindowState: false,
    shadow: true,
    showTaskbarIcon: true,
    url: ROUTES.LOGIN,
    waitForPageLoad: true,
  },
};

export default config;
