import { APP_DIRECTORY_WINDOW, APP_LAUNCHER_OVERFLOW_WINDOW, CONTEXT_MENU, LAYOUTS_WINDOW, LOGOUT_WINDOW, SETTINGS_WINDOW } from '../../config/windows';

export const EXPANDED_LAUNCHER_WINDOWS_SHOWING = [
  APP_DIRECTORY_WINDOW,
  APP_LAUNCHER_OVERFLOW_WINDOW,
  CONTEXT_MENU,
  LAYOUTS_WINDOW,
  LOGOUT_WINDOW,
  SETTINGS_WINDOW,
];
