import { UserLayout, Workspace } from '../../types/commons';
import { createAction, createAsyncActionCreators } from '../utils';
import { CreateOrUpdateSuccessPayload, GetLayoutsSuccessPayload, UpdateLayoutRequestPayload } from './types';

// Action types
// GET_LAYOUTS
const GET_LAYOUTS_REQUEST = 'GET_LAYOUTS_REQUEST';
const GET_LAYOUTS_SUCCESS = 'GET_LAYOUTS_SUCCESS';
const GET_LAYOUTS_FAILURE = 'GET_LAYOUTS_FAILURE';

// SHARE_LAYOUT
const SHARE_LAYOUT_REQUEST = 'SHARE_LAYOUT_REQUEST';
const SHARE_LAYOUT_SUCCESS = 'SHARE_LAYOUT_SUCCESS';
const SHARE_LAYOUT_FAILURE = 'SHARE_LAYOUT_FAILURE';

// RESTORE_LAYOUT
const RESTORE_LAYOUT_REQUEST = 'RESTORE_LAYOUT_REQUEST';
const RESTORE_LAYOUT_SUCCESS = 'RESTORE_LAYOUT_SUCCESS';
const RESTORE_LAYOUT_FAILURE = 'RESTORE_LAYOUT_FAILURE';
// CREATE_LAYOUT
const CREATE_LAYOUT_REQUEST = 'CREATE_LAYOUT_REQUEST';
const CREATE_LAYOUT_SUCCESS = 'CREATE_LAYOUT_SUCCESS';
const CREATE_LAYOUT_FAILURE = 'CREATE_LAYOUT_FAILURE';
// DISMISS_UNDO_UPDATE_LAYOUT
const DISMISS_UNDO_UPDATE_LAYOUT_REQUEST = 'DISMISS_UNDO_UPDATE_LAYOUT_REQUEST';
const DISMISS_UNDO_UPDATE_LAYOUT_SUCCESS = 'DISMISS_UNDO_UPDATE_LAYOUT_SUCCESS';
const DISMISS_UNDO_UPDATE_LAYOUT_FAILURE = 'DISMISS_UNDO_UPDATE_LAYOUT_FAILURE';
// UNDO_UPDATE_LAYOUT
const UNDO_UPDATE_LAYOUT_REQUEST = 'UNDO_UPDATE_LAYOUT_REQUEST';
const UNDO_UPDATE_LAYOUT_SUCCESS = 'UNDO_UPDATE_LAYOUT_SUCCESS';
const UNDO_UPDATE_LAYOUT_FAILURE = 'UNDO_UPDATE_LAYOUT_FAILURE';
// UPDATE_LAYOUT
const UPDATE_LAYOUT_REQUEST = 'UPDATE_LAYOUT_REQUEST';
const UPDATE_LAYOUT_SUCCESS = 'UPDATE_LAYOUT_SUCCESS';
const UPDATE_LAYOUT_FAILURE = 'UPDATE_LAYOUT_FAILURE';
// DELETE_LAYOUT
const DELETE_LAYOUT_REQUEST = 'DELETE_LAYOUT_REQUEST';
const DELETE_LAYOUT_SUCCESS = 'DELETE_LAYOUT_SUCCESS';
const DELETE_LAYOUT_FAILURE = 'DELETE_LAYOUT_FAILURE';
// SAVE_LAYOUT
const SAVE_LAYOUT_REQUEST = 'SAVE_LAYOUT_REQUEST';
const SAVE_LAYOUT_SUCCESS = 'SAVE_LAYOUT_SUCCESS';
const SAVE_LAYOUT_FAILURE = 'SAVE_LAYOUT_FAILURE';
// RESET_LAYOUTS
const RESET_LAYOUTS = 'RESET_LAYOUTS';

// Action creators
export const getLayouts = createAsyncActionCreators(GET_LAYOUTS_REQUEST, GET_LAYOUTS_SUCCESS, GET_LAYOUTS_FAILURE)<void, GetLayoutsSuccessPayload, Error>();
export const restoreLayout = createAsyncActionCreators(RESTORE_LAYOUT_REQUEST, RESTORE_LAYOUT_SUCCESS, RESTORE_LAYOUT_FAILURE)<
  UserLayout['id'],
  Workspace,
  Error
>();
export const createLayout = createAsyncActionCreators(CREATE_LAYOUT_REQUEST, CREATE_LAYOUT_SUCCESS, CREATE_LAYOUT_FAILURE)<
  UserLayout['name'],
  CreateOrUpdateSuccessPayload,
  Error
>();
export const dismissUndoUpdateLayout = createAsyncActionCreators(
  DISMISS_UNDO_UPDATE_LAYOUT_REQUEST,
  DISMISS_UNDO_UPDATE_LAYOUT_SUCCESS,
  DISMISS_UNDO_UPDATE_LAYOUT_FAILURE,
)<void, void, Error>();
export const undoUpdateLayout = createAsyncActionCreators(UNDO_UPDATE_LAYOUT_REQUEST, UNDO_UPDATE_LAYOUT_SUCCESS, UNDO_UPDATE_LAYOUT_FAILURE)<
  void,
  void,
  Error
>();
export const updateLayout = createAsyncActionCreators(UPDATE_LAYOUT_REQUEST, UPDATE_LAYOUT_SUCCESS, UPDATE_LAYOUT_FAILURE)<
  UpdateLayoutRequestPayload,
  CreateOrUpdateSuccessPayload,
  Error
>();
export const deleteLayout = createAsyncActionCreators(DELETE_LAYOUT_REQUEST, DELETE_LAYOUT_SUCCESS, DELETE_LAYOUT_FAILURE)<
  UserLayout['id'],
  UserLayout['id'],
  Error
>();
export const saveLayout = createAsyncActionCreators(SAVE_LAYOUT_REQUEST, SAVE_LAYOUT_SUCCESS, SAVE_LAYOUT_FAILURE)<
  UserLayout['name'],
  CreateOrUpdateSuccessPayload,
  Error
>();
export const shareLayout = createAsyncActionCreators(SHARE_LAYOUT_REQUEST, SHARE_LAYOUT_SUCCESS, SHARE_LAYOUT_FAILURE)<
  UserLayout['id'],
  {link: string},
  Error
>();
export const resetLayouts = createAction(RESET_LAYOUTS)();
