swagger: '2.0'

host: 'localhost:8081'

basePath: /api

info:
  title: whiteboard api
  version: 0.0.1

paths:

  /config:
    get:
      summary: Get Configuration
      description: theme settings, etc

      responses:
        '200':
          description: Configuration
          schema:
            $ref: '#/definitions/Config'
        '404':
          description: Configuration not found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'


  /auth/login:
    post:
      summary: Login

      tags:
        - Auth

      parameters:
        - description: Login credentials json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/Login'

      responses:
        '200':
          description: Login Successful
          schema:
            $ref: '#/definitions/CurrentUserProperties'
        '401':
          description: Login Unsuccessful
          schema:
            $ref: '#/definitions/AuthChallengeError'

  /auth/logout:
    post:
      summary: Logout

      tags:
        - Auth

      responses:
        '200':
          description: Logout Successful
        '500':
          description: Logout Unsuccessful (not currently logged in?)
          schema:
            $ref: '#/definitions/ServerError'

  /auth/password/new:
    post:
      summary: New Password

      tags:
        - Auth

      parameters:
        - description: New password json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/NewPassword'

      responses:
        '200':
          description: Password update successful
          schema:
            $ref: '#/definitions/CurrentUserProperties'
        '401':
          description: Password update unsuccessful
          schema:
            $ref: '#/definitions/AuthChallengeError'
        '400':
          description: Bad Request

  /auth/password/change:
    post:
      summary: Change Password

      tags:
        - Auth

      parameters:
        - description: Change password json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/ChangePassword'

      responses:
        '200':
          description: Password update successful
        '400':
          description: Bad Request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /auth/password/forgot:
    post:
      summary: Forgot Password

      tags:
        - Auth

      responses:
        '200':
          description: Password update successful
        '400':
          description: Bad Request
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /auth/password/confirm:
    post:
      summary: Confirm Forgot Password

      tags:
        - Auth

      parameters:
        - description: Change password json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/ConfirmPassword'

      responses:
        '200':
          description: Password update successful
        '400':
          description: Bad Request
        '401':
          description: Password forgot failed


  /user/layouts:
    get:
      summary: Get Layouts

      tags:
        - User

      responses:
        '200':
          description: Layout List
          schema:
            title: layouts array
            type: array
            items:
              $ref: '#/definitions/Layout'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    post:
      summary: Save New Layout

      tags:
        - User

      parameters:
        - description: Layout json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/NewLayout'

      responses:
        '200':
          description: Layout Saved
          schema:
            $ref: '#/definitions/Layout'
        '400':
          description: Bad Request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /user/layouts/{name}:
    get:
      summary: Get Layout

      tags:
        - User

      parameters:
        - in: path
          required: true
          name: name
          type: string

      responses:
        '200':
          description: Layout
          schema:
            $ref: '#/definitions/Layout'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '404':
          description: Layout not Found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    put:
      summary: Update Layout

      tags:
        - User

      parameters:
        - in: path
          required: true
          name: name
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Layout'
          description: Layout json

      responses:
        '200':
          description: Layout Updated
          schema:
            $ref: '#/definitions/Layout'
        '400':
          description: Bad Request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '404':
          description: Layout not Found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    delete:
      summary: Delete Layout

      tags:
        - User

      parameters:
        - in: path
          required: true
          name: name
          type: string

      responses:
        '200':
          description: Layout Deleted
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '404':
          description: Layout not Found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /user/settings:
    get:
      summary: Get User Settings

      tags:
        - User

      responses:
        '200':
          description: Settings Object
          schema:
            $ref: '#/definitions/Settings'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    post:
      summary: Save User Settings

      tags:
        - User

      parameters:
        - description: Settings json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/Settings'

      responses:
        '200':
          description: Settings saved
        '400':
          description: Bad request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'


  /admin/users:
    get:
      summary: Get Users

      tags:
        - Admin

      responses:
        '200':
          description: User List
          schema:
            title: Users array
            type: array
            items:
              $ref: '#/definitions/AdminUserProperties'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    post:
      summary: Create User

      tags:
        - Admin

      parameters:
        - description: User payload
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/AdminCreateUserProperties'

      responses:
        '200':
          description: User created
        '400':
          description: Bad request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /admin/users/bulk:
    post:
      summary: Create Users

      tags:
        - Admin

      parameters:
        - description: Users payload
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/AdminCreateUsersProperties'

      responses:
        '200':
          description: Request Successful, read on further
          schema:
            $ref: '#/definitions/AdminCreateUsersResponse'
        '400':
          description: Bad request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /admin/users/{id}:
    get:
      summary: Get User

      tags:
        - Admin

      parameters:
        - in: path
          required: true
          name: id
          type: string

      responses:
        '200':
          description: User
          schema:
            $ref: '#/definitions/AdminUserProperties'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '404':
          description: User not Found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    put:
      summary: Update User

      tags:
        - Admin

      parameters:
        - in: path
          required: true
          name: id
          type: string
        - in: body
          name: body
          description: User Payload
          required: true
          schema:
            $ref: '#/definitions/AdminUpdateUserProperties'

      responses:
        '200':
          description: User updated
        '400':
          description: Bad request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '404':
          description: User not Found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    delete:
      summary: Delete User

      tags:
        - Admin

      parameters:
        - in: path
          required: true
          name: id
          type: string

      responses:
        '200':
          description: User deleted
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '404':
          description: User not Found
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /admin/settings:
    get:
      summary: Get Org Settings

      tags:
        - Admin

      responses:
        '200':
          description: Settings Object
          schema:
            $ref: '#/definitions/Settings'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    post:
      summary: Save Org Settings

      tags:
        - Admin

      parameters:
        - description: Settings json
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/Settings'

      responses:
        '200':
          description: Settings saved
        '400':
          description: Bad request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

  /admin/manifest:
    get:
      summary: Get Org Manifest Overrides

      tags:
        - Admin

      responses:
        '200':
          description: Manifest Overrides Object
          schema:
            $ref: '#/definitions/Manifest'
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'

    post:
      summary: Save Org Manifest Overrides

      tags:
        - Admin

      parameters:
        - description: Manifest json (partial/overlay)
          required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/Manifest'

      responses:
        '200':
          description: Settings saved
        '400':
          description: Bad request
        '401':
          description: Access Denied
          schema:
            $ref: '#/definitions/AuthError'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/ServerError'


definitions:
  Login:
    title: Login credentials payload
    type: object
    properties:
      username:
        type: string
        description: Username (email)
      password:
        type: string
        description: Password
    required:
      - username
      - password

  NewPassword:
    title: New password and credentials payload
    type: object
    properties:
      username:
        type: string
        description: Username (email)
      session:
        type: string
        description: Old Password
      newPassword:
        type: string
        description: New Password
      fields:
        type: object
        description: required fields
    required:
      - username
      - password
      - newPassword
      - session

  ChangePassword:
    title: Change password payload
    type: object
    properties:
      password:
        type: string
        description: Old Password
      newPassword:
        type: string
        description: New Password
    required:
      - password
      - newPassword

  ConfirmPassword:
    title: Confirm forgot password payload
    type: object
    properties:
      password:
        type: string
        description: Old Password
      newPassword:
        type: string
        description: New Password
    required:
      - password
      - newPassword

  Layout:
    title: layout json request payload
    type: object
    properties:
      name:
        type: string
        description: layout name
      layout:
        type: object
        description: layout data

  NewLayout:
    title: layout json request payload
    type: object
    properties:
      name:
        type: string
        description: layout name
      layout:
        type: object
        description: layout data

  ServerError:
    title: general server error payload
    type: object
    properties:
      status:
        type: string
        description: error status/type
      code:
        type: string
        description: error code
      message:
        type: string
        description: error message

  AuthError:
    title: authentication error payload
    allOf: 
      - $ref: '#/definitions/ServerError'

  CreateUsersError:
    title: user creation error
    allOf: 
      - $ref: '#/definitions/ServerError'
      - properties:
          row:
            type: number
            description: index of user that created the error

  AuthChallengeError:
    title: authentication challenge error
    type: object
    properties:
      status:
        type: string
        description: challenge type
      message:
        type: string
        description: error message
      session:
        type: string
        description: challenge session id
      requiredFields:
        type: array
        description: any required user properties (initial login)
        items:
          type: string

  CurrentUserProperties:
    title: current user properties payload
    type: object
    properties:
      email:
        type: string
        description: email
      firstName:
        type: string
        description: first name
      lastName:
        type: string
        description: last name
      phone:
        type: string
        description: phone number
      isAdmin:
        type: boolean
        description: user is an admin

  AdminUserProperties:
    title: admin users properties
    type: object
    properties:
      username:
        type: string
        description: user GUID
      email:
        type: string
        description: email
      firstName:
        type: string
        description: first name
      lastName:
        type: string
        description: last name
      phone:
        type: string
        description: phone number
      isAdmin:
        type: boolean
        description: user is an admin
      created:
        type: string
        description: user created at
      lastModified:
        type: string
        description: user last modified at
      status:
        type: string
        description: user status
      enabled:
        type: boolean
        description: user enabled

  CreateUserBase:
    title: base create user properties
    type: object
    properties:
      email:
        type: string
        description: email
      firstName:
        type: string
        description: first name
      lastName:
        type: string
        description: last name
      phone:
        type: string
        description: phone number
      tmpPassword:
        type: string
        description: temporary password
    required:
      - email
      - tmpPassword
    
  AdminCreateUserProperties:
    title: admin create user properties
    allOf: 
      - $ref: '#/definitions/CreateUserBase'
      - properties:
          sendEmail:
            type: boolean
            description: send user a welcome email

  AdminCreateUsersProperties:
    title: admin create users properties
    type: object
    properties:
      users:
        type: array
        items:
          $ref: '#/definitions/CreateUserBase'
        description: array of users to create
      sendEmail:
        type: boolean
        description: send user a welcome email

  AdminCreateUsersResponse:
    title: admin create users properties
    type: object
    properties:
      users:
        type: array
        items:
          $ref: '#/definitions/AdminUserProperties'
        description: array of users to create
      errors:
        type: array
        items:
          $ref: '#/definitions/CreateUsersError'
        description: array of errors (if any)
      status:
        type: string
        description: status (ok == all users created, error == 1 or more errors encountered)

  AdminUpdateUserProperties:
    title: admin users properties
    type: object
    properties:
      firstName:
        type: string
        description: first name
      lastName:
        type: string
        description: last name
      phone:
        type: string
        description: phone number

  Config:
    title: 'organization configuration (theme, etc)'
    type: object
    properties:
      config:
        type: object

  Settings:
    title: user settings
    type: object
    properties:
      settings:
        type: object
        description: user settings object

  Manifest:
    title: OpenFin manifest (partial/overlay)
    type: object