// Styleguide
import '../src/styles/styles.story';

// UI Components - should have not be connected to the store in any way
import '../src/components/AppIcon/AppIcon.story';
import '../src/components/AppIndicator/AppIndicator.story';
import '../src/components/Borders/Borders.story';
import '../src/components/Button/Button.story';
import '../src/components/ButtonTile/ButtonTile.story';
import '../src/components/Checkbox/Checkbox.story';
import '../src/components/CloseButton/CloseButton.story';
import '../src/components/ErrorMessage/ErrorMessage.story';
import '../src/components/FormField/FormField.story';
import '../src/components/ImageCard/ImageCard.story';
import '../src/components/ImageInput/ImageInput.story';
import '../src/components/ImagePreview/ImagePreview.story';
import '../src/components/Input/Input.story';
import '../src/components/Label/Label.story';
import '../src/components/Link/Link.story';
import '../src/components/Loading/Loading.story';
import '../src/components/Logo/Logo.story';
import '../src/components/MessageBanner/MessageBanner.story';
import '../src/components/RadioButton/RadioButton.story';
import '../src/components/Responsive/ScrollGrid.story';
import '../src/components/SearchInput/SearchInput.story';
import '../src/components/SvgIcon/SvgIcon.story';
import '../src/components/Tabs/Tabs.story';
import '../src/components/WindowHeader/WindowHeader.story';

// Components
import '../src/components/AccountSettings/AccountSettings.story';
import '../src/components/App/App.story';
import '../src/components/AppCard/AppCard.story';
import '../src/components/AppDirectory/AppDirectory.story';
import '../src/components/AppList/AppList.story';
import '../src/components/AppListToggle/AppListToggle.story';
import '../src/components/AppOverflow/AppOverflow.story';
import '../src/components/ChangePasswordForm/ChangePasswordForm.story';
import '../src/components/ConfirmPasswordUpdate/ConfirmPasswordUpdate.story';
import '../src/components/DirectionControls/DirectionControls.story';
import '../src/components/ForgotPassword/ForgotPassword.story';
import '../src/components/ForgotPasswordChangeForm/ForgotPasswordChangeForm.story';
import '../src/components/ForgotPasswordRequestForm/ForgotPasswordRequestForm.story';
import '../src/components/ForgotPasswordSuccess/ForgotPasswordSuccess.story';
import '../src/components/FormWindow/FormWindow.story';
import '../src/components/LauncherAppIcon/LauncherAppIcon.story';
import '../src/components/LauncherSettings/LauncherSettings.story';
import '../src/components/Layouts/Layouts.story';
import '../src/components/LayoutsList/LayoutsList.story';
import '../src/components/LayoutsListItem/LayoutsListItem.story';
import '../src/components/LayoutsUserActions/LayoutsUserActions.story';
import '../src/components/Login/Login.story';
import '../src/components/LoginForm/LoginForm.story';
import '../src/components/Logout/Logout.story';
import '../src/components/MonitorControls/MonitorControls.story';
import '../src/components/MonitorControlsDialog/MonitorControlsDialog.story';
import '../src/components/NotificationsIcon/NotificationsIcon.story';
import '../src/components/PasswordForm/PasswordForm.story';
import '../src/components/Settings/Settings.story';
import '../src/components/SvgIconWithExtension/SvgIconWithExtension.story';
import '../src/components/SystemDrawer/SystemDrawer.story';
import '../src/components/UpdatePasswordForm/UpdatePasswordForm.story';

// Admin Components
import '../src/components/Admin/Admin.story';
import '../src/components/AdminApps/AdminApps.story';
import '../src/components/AdminConfirmation/AdminConfirmation.story';
import '../src/components/AdminUsers/AdminUsers.story';
import '../src/components/AppForm/AppForm.story';
import '../src/components/ConfirmAppDelete/ConfirmAppDelete.story';
import '../src/components/ConfirmRevertImage/ConfirmRevertImage.story';
import '../src/components/ConfirmUserDelete/ConfirmUserDelete.story';
import '../src/components/EditAppForm/EditAppForm.story';
import '../src/components/EditAppWindow/EditAppWindow.story';
import '../src/components/EditUserForm/EditUserForm.story';
import '../src/components/EditUserWindow/EditUserWindow.story';
import '../src/components/ImageForm/ImageForm.story';
import '../src/components/ImageUpload/ImageUpload.story';
import '../src/components/NewAppForm/NewAppForm.story';
import '../src/components/NewAppWindow/NewAppWindow.story';
import '../src/components/NewUserForm/NewUserForm.story';
import '../src/components/NewUserWindow/NewUserWindow.story';
import '../src/components/OrganizationSettings/OrganizationSettings.story';
import '../src/components/ThemesForm/ThemesForm.story';
import '../src/components/UserCard/UserCard.story';
import '../src/components/UserForm/UserForm.story';

// Layouts Service
import '../src/layoutsService/LayoutsService.story';
