/* tslint:disable */
export default [
  {
    id: 1,
    username: 'username1',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'John',
    lastName: 'Doe',
    middleInitial: 'M1',
    organizationId: 'o1',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 2,
    username: 'username2',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Ashley',
    lastName: 'Williams',
    middleInitial: 'M2',
    organizationId: 'o2',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 3,
    username: 'username3',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Matt',
    lastName: 'Taylor',
    middleInitial: 'M3',
    organizationId: 'o3',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 4,
    username: 'username4',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Dan',
    lastName: 'Johnson',
    middleInitial: 'M4',
    organizationId: 'o4',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 5,
    username: 'username5',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Andy',
    lastName: 'Moore',
    middleInitial: 'M5',
    organizationId: 'o5',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 6,
    username: 'username6',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Jose',
    lastName: 'Conseco',
    middleInitial: 'M6',
    organizationId: 'o6',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 7,
    username: 'username7',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Jon',
    lastName: 'Fire',
    middleInitial: 'M7',
    organizationId: 'o7',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 8,
    username: 'username8',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'James',
    lastName: 'Knot',
    middleInitial: 'M8',
    organizationId: 'o8',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 9,
    username: 'username9',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Guillermo',
    lastName: 'Del Toro',
    middleInitial: 'M9',
    organizationId: 'o9',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
  {
    id: 10,
    username: 'username10',
    password: '123',
    email: 'test@gmail.com',
    firstName: 'Robert',
    lastName: 'Martin',
    middleInitial: 'M10',
    organizationId: 'o10',
    isAdmin: true,
    isInitialized: true,
    dateStarted: 'Thu Nov 15 2018',
  },
];
